{% set version = "0.1.3" %}

package:
  name: pymt_cem
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_cem/archive/v{{ version }}.tar.gz
  sha256: aad2cd9bc165979dd410a0eba2ad14037d77b24cc69a963ba683878e5c21aaff

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - model_metadata
    - cem

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cem

test:
  imports:
    - pymt_cem

about:
  home: https://github.com/pymt-lab/pymt_cem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CEM components wrapped as PyMT plugins.
  dev_url: https://github.com/pymt-lab/pymt_cem

extra:
  recipe-maintainers:
    - mcflugen
